gems:
  - bourbon
  - neat
  - octopress-autoprefixer
  - jekyll-assets

# Structure configuration
source: source
destination: build

assets:
  cachebust: soft
  sources:
    - _assets/css
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/img
    - _assets/js

# Site settings
title: Jekyll Starter
description: Prototyping starter kit for Jekyll

# Name of project on Github
baseurl: /proteus-jekyll

# Build settings
markdown: kramdown

twitter_username: jekyllrb
github_username:  jekyll
